/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package factorypractice.labtwo;

import java.text.DecimalFormat;
import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author Mike
 */
public class MainWindow extends javax.swing.JFrame {
    final AbstractApplicationContext ctx = 
                new ClassPathXmlApplicationContext("applicationContext.xml");
    TipService service = null; 
    private DecimalFormat formatter = new DecimalFormat("#0.00");
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboCalculatorSelector = new javax.swing.JComboBox<>();
        comboServiceQualitySelector = new javax.swing.JComboBox<>();
        txtValueInput = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblCalculatorName = new javax.swing.JLabel();
        lblValueDescriptor = new javax.swing.JLabel();
        lblServiceQuality = new javax.swing.JLabel();
        lblTotalTip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboCalculatorSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food Service", "Baggage Service" }));
        comboCalculatorSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCalculatorSelectorActionPerformed(evt);
            }
        });

        comboServiceQualitySelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOOD", "FAIR", "POOR" }));

        txtValueInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueInputActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblCalculatorName.setText("Select Calculator:");

        lblValueDescriptor.setText("Enter Total Bill Amount:");

        lblServiceQuality.setText("Select Service Quality:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTotalTip, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCalculatorName)
                            .addComponent(lblValueDescriptor)
                            .addComponent(lblServiceQuality))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCalculatorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboServiceQualitySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCalculatorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalculatorName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueDescriptor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboServiceQualitySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceQuality))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalTip, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCalculatorSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCalculatorSelectorActionPerformed
       switch(comboCalculatorSelector.getSelectedIndex()){
            case 0: 
                lblValueDescriptor.setText("Enter Total Bill Amount:");
                break;
            case 1:
                lblValueDescriptor.setText("Enter Total Bag Amount:");
                break;
        }
    }//GEN-LAST:event_comboCalculatorSelectorActionPerformed

    private void txtValueInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueInputActionPerformed
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        switch(comboCalculatorSelector.getSelectedIndex()){
            case 0: 
                service = (TipService)ctx.getBean("foodServiceCalculator");
                break;
            case 1:
                service = (TipService)ctx.getBean("baggageServiceCalculator");
                break;
        }
        
        switch(comboServiceQualitySelector.getSelectedIndex()){
            case 0:
                service.getTipCalculator().setServiceQuality(ServiceQuality.GOOD);
                break;
            case 1:
                service.getTipCalculator().setServiceQuality(ServiceQuality.FAIR);
                break;
            case 2:
                service.getTipCalculator().setServiceQuality(ServiceQuality.POOR);
                break;
        }              
             
        switch(comboCalculatorSelector.getSelectedIndex()){
            case 0:
                service.getTipCalculator().setInputData(Double.valueOf(txtValueInput.getText()));
                lblTotalTip.setText("The food service tip is calculated to be: " + formatter.format(service.getTip()));
                break;
            case 1:
                service.getTipCalculator().setInputData(Integer.valueOf(txtValueInput.getText()));
                lblTotalTip.setText("The baggage handler tip is calculated to be: " + formatter.format(service.getTip()));
                break;
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboCalculatorSelector;
    private javax.swing.JComboBox<String> comboServiceQualitySelector;
    private javax.swing.JLabel lblCalculatorName;
    private javax.swing.JLabel lblServiceQuality;
    private javax.swing.JLabel lblTotalTip;
    private javax.swing.JLabel lblValueDescriptor;
    private javax.swing.JTextField txtValueInput;
    // End of variables declaration//GEN-END:variables
}
